### ISSUE TITLE
Arquivo de escolha de tipos de variáveis/parâmetros/etc.

### ISSUE THREAD

**Issue by mkanada** [mkanada/osmdconverter#3]
JavaScript é uma linguagem não tipada, e TypeScript possui um número bem limitado de tipos básicos. Isto quer dizer que, na geração para Dart, algumas escolhas tem que ser feitas. Pode ser difícil, ou até impossível encontrar a melhor escolha para uma determinada variável, parâmetro, etc.

Criar um arquivo de configuração onde isto pode ser descrito e usado no momento de geração.

**Comment by mkanada** [comment]
O diretório onde fica o OSMD original deverá ser reescrito ao longo do tempo, a cada versão nova que o OSMD for lançado. Então este diretório original não é um bom local para colocar este arquivo de configuração. O diretório de saída também poderá ser reescrito a cada geração, fazendo que o diretório de saída também não seja uma boa opção.

Então, talvez, o melhor seja um único arquivo próximo à raiz do projeto.

**Comment by mkanada** [comment]
YAML exemplo:

```
---
my/directory/file.dart:
  doubleValues:
    globalVariables:
      - var1
      - var2
      - var3
    functions:
      - myFunction:
          parameters:
            - param1
            - param3
      - myFunction2:
          parameters:
            - param1
          returnType: true
    classes:
      - class1:
          fields:
            - field1
          methods:
            - method1:
                parameters:
                  - param1
my/directory/file2.dart:
  doubleValues:
    classes:
      - class1:
          fields:
            - field1
          methods:
            - method1:
                parameters:
                  - param1
```
